name: DehydrationPlugin
version: '1.0'
main: me.sander.dehydrationplugin.DehydrationPlugin
api-version: '1.20'
commands:
  givedatacontainer:
    description: Give a data container to the player
    usage: /givedatacontainer
